version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/workspace/aws-cicd
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/codedeploy/AfterInstall.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/codedeploy/ApplicationStart.sh
      timeout: 60
      runas: ec2-user
